version: "3.9"

networks:
  mecare-network:
    driver: bridge

volumes:
  pgdata:
  redis-cache:
  redis-insight:


services:
  # Postgres Database
  user_service_db:
    image: postgres
    restart: always
    ports:
      - "5133:5432" # Maps container 5432 to host 5133
    environment:
      POSTGRES_DB: users
      POSTGRES_USER: mecare
      POSTGRES_PASSWORD: root
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - mecare-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U mecare" ]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis
  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-cache:/data
    networks:
      - mecare-network
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

  # RedisInsight
  redis-insight:
    image: redis/redisinsight:latest
    restart: always
    ports:
      - "5540:5540"
    environment:
      RI_HOST: 0.0.0.0
    depends_on:
      redis:
        condition: service_healthy
    volumes:
      - redis-insight:/data
    networks:
      - mecare-network
  kafka:
    image: apache/kafka:latest
    container_name: kafka
    ports:
      - "9094:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: >
        PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:9095,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: >
        PLAINTEXT://localhost:9094,PLAINTEXT_HOST://kafka:9095
      # MAP listener names
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER

      # KRaft
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093

      # Single-node
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "8000:8080"
    depends_on:
      - kafka
      - schema-registry
    environment:
      KAFKA_CLUSTERS_0_NAME: local-kafka
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9095
      KAFKA_CLUSTERS_0_SCHEMA_REGISTRY_URL: http://schema-registry:8081

  schema-registry:
    image: confluentinc/cp-schema-registry:8.0.3
    container_name: schema-registry
    depends_on:
      - kafka
    ports:
      - "8083:8081"
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: kafka:9095
